### ISSUE TITLE
Install breaks with Fatal Error: Call to member function setCnild()  on null

### ISSUE THREAD

**Issue by gusev-genotek** [merlinthemagic/MTS#28]
```
root@ec0f866a369a:/var/www/html/vendor/merlinthemagic/mts# php MtsSetup.php
We do not know which user you intend to execute the scripts with
All example commands use '$userName' as the user, please replace with
the username you intent to use.
Fatal error: Uncaught Error: Call to a member function setChild() on null in /var/www/html/vendor/merlinthemagic/mts/MTS/Factories/Files.php:
19
Stack trace:
#0 /var/www/html/vendor/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/PhpEnvironment.php(52): MTS\Factories\Files->getFile('', '')
#1 /var/www/html/vendor/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/PhpEnvironment.php(16): MTS\Common\Devices\Actions\Local\Hos
t\PhpEnvironment->execute()
#2 /var/www/html/vendor/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/MtsSetup/SetupMTS.php(130): MTS\Common\Devices\Actions\Local
\Host\PhpEnvironment->getIniFile()
#3 /var/www/html/vendor/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/MtsSetup/SetupMTS.php(14): MTS\Common\Devices\Actions\Local\
Host\MtsSetup\SetupMTS->timezoneValid()
#4 /var/www/html/vendor/merlinthemagic/mts/MtsSetup.php(18): MTS\Common\Devices\Actions\Local\Host\MtsSetup\SetupMTS->getInstall()
#5 {main}
  thrown in /var/www/html/vendor/merlinthemagic/mts/MTS/Factories/Files.php on line 19
```

**Comment by gusev-genotek** [comment]
If I ran it from the web I get another error:

```

Notice: Undefined variable: dirObj in /var/www/html/vendor/merlinthemagic/mts/MTS/Factories/Files.php on line 44

Fatal error: Uncaught Error: Call to a member function setChild() on null in /var/www/html/vendor/merlinthemagic/mts/MTS/Factories/Files.php:19 Stack trace: #0 /var/www/html/vendor/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/PhpEnvironment.php(52): MTS\Factories\Files->getFile('', '') #1 /var/www/html/vendor/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/PhpEnvironment.php(16): MTS\Common\Devices\Actions\Local\Host\PhpEnvironment->execute() #2 /var/www/html/vendor/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/MtsSetup/SetupMTS.php(130): MTS\Common\Devices\Actions\Local\Host\PhpEnvironment->getIniFile() #3 /var/www/html/vendor/merlinthemagic/mts/MTS/Common/Devices/Actions/Local/Host/MtsSetup/SetupMTS.php(14): MTS\Common\Devices\Actions\Local\Host\MtsSetup\SetupMTS->timezoneValid() #4 /var/www/html/frontend/web/MtsSetup.php(83): MTS\Common\Devices\Actions\Local\Host\MtsSetup\SetupMTS->getInstall() #5 {main} thrown in /var/www/html/vendor/merlinthemagic/mts/MTS/Factories/Files.php on line 19
```

**Comment by merlinthemagic** [comment]
Hi,

Are you using master or a release?

What OS are you using, version and architecture.

Mm

**Comment by gusev-genotek** [comment]
I am using release (installed via composer) on debian jessie

**Comment by merlinthemagic** [comment]
Could you please run this command and post the output here:

`$rData		= php_ini_loaded_file();`

i updated master to check that PHP has php.ini loaded, we need it to ensure the timezone of the server is set correctly.

**Comment by merlinthemagic** [comment]
@gusev-genotek did you resolve the issue? If so what was the problem?
