### ISSUE TITLE
Bash::shellStrExecute>> Read data timeout

### ISSUE THREAD

**Issue by ostrolucky** [merlinthemagic/MTS#43]
After ensuring `screen` is installed, I get this when using code from example to connect to remote host.

```
PHP Fatal error:  Uncaught Exception: MTS\Common\Devices\Shells\Bash::shellStrExecute>> Read data timeout in /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Bash.php:81
Stack trace:
#0 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Base.php(89): MTS\Common\Devices\Shells\Bash->shellStrExecute('\x03\r', '\\[bash\\.5bc1f68...', 10000)
#1 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Bash.php(252): MTS\Common\Devices\Shells\Base->exeCmd('\x03\r')
#2 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Base.php(105): MTS\Common\Devices\Shells\Bash->shellKillLastProcess()
#3 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php(76): MTS\Common\Devices\Shells\Base->killLastProcess()
#4 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php(47): MTS\Common\Devices\Actions\Remote\Connections\Ssh->connectByUsernameFromLinux(Object(MTS\Common\Devices\Shells\Bash), 'redacted', 'redacted', 'redacted', 22, 30000)
#5 /home/g9735/IdeaProjects/mts/MTS/Common/ in /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Bash.php on line 81
PHP Fatal error:  Uncaught Exception: MTS\Common\Devices\Shells\Bash::shellStrExecute>> Read data timeout in /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Bash.php:81
Stack trace:
#0 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Base.php(89): MTS\Common\Devices\Shells\Bash->shellStrExecute('\x03\r', '\\[bash\\.5bc1f68...', 10000)
#1 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Bash.php(252): MTS\Common\Devices\Shells\Base->exeCmd('\x03\r')
#2 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Base.php(105): MTS\Common\Devices\Shells\Bash->shellKillLastProcess()
#3 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Bash.php(223): MTS\Common\Devices\Shells\Base->killLastProcess()
#4 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Base.php(148): MTS\Common\Devices\Shells\Bash->shellTerminate()
#5 /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Shells/Base.php(28): MTS\Common\Devices\Shells\Base->terminate()
#6 [internal function]: MTS\Common\Devices\Shells\Base->__destruct()
#7 {main}
```

**Comment by merlinthemagic** [comment]
is this related to [Issue?](https://github.com/merlinthemagic/MTS/issues/42)

**Comment by ostrolucky** [comment]
I solved referenced issue by installing screen. You should resolve that issue by fixing the validation.

This issue is indeed continuation of previous issue, but I don't see how are they related. This is different problem.
