### ISSUE TITLE
Don't enforce connection via username:password

### ISSUE THREAD

**Issue by ostrolucky** [merlinthemagic/MTS#44]
I'm using authentication via SSH keys instead of username/password. MTS does not support it, because it throws exception when missing username/password;

```php
$shellObj = \MTS\Factories::getDevices()->getRemoteHost('redacted')->getShell();
```

```
PHP Fatal error:  Uncaught Exception: MTS\Common\Devices\Types\Remotehost::getShell>> Missing Connection details in /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Types/Remotehost.php:80
Stack trace:
#0 /home/g9735/IdeaProjects/mts/index.php(5): MTS\Common\Devices\Types\Remotehost->getShell()
#1 {main}
  thrown in /home/g9735/IdeaProjects/mts/MTS/Common/Devices/Types/Remotehost.php on line 80
```

**Comment by merlinthemagic** [comment]
ya thats an easy fix. If password === null expect pub key auth. ill push

**Comment by merlinthemagic** [comment]
Clone master again. Let me know if it works.

**Comment by ostrolucky** [comment]
```
PHP Fatal error:  Uncaught Exception: MTS\Common\Devices\Actions\Remote\Connections\Ssh::connectByUsernameFromLinux>> Not Handled for Request Type: connectByUsername in /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php:129
Stack trace:
#0 /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php(47): MTS\Common\Devices\Actions\Remote\Connections\Ssh->connectByUsernameFromLinux(Object(MTS\Common\Devices\Shells\Bash), 'user', NULL, 'example.com', 22, 30000)
#1 /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php(18): MTS\Common\Devices\Actions\Remote\Connections\Ssh->execute()
#2 /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Types/Remotehost.php(73): MTS\Common\Devices\Actions\Remote\Connections\Ssh->connectByUsername(Object(MTS\Common\Devices\Shells\Bash), 'potkany', NULL, 'sdaj.mtf.stuba....', 22)
#3 /home/g9735/IdeaProjects/MTS/index.php(5): MTS\Common\Devices\Types\Remotehost->getShell()
#4 {main}
  thrown in /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php on line 129
```

Also, can't you make your stack traces anonymized? It's annoying and risky to always anonymize it by hand after the fact. There is highly sensitive info there!

**Comment by merlinthemagic** [comment]
Try master once more, if it fails then do a login by hand from the terminal and post what shows in the terminal here.

And no you can't pass a string to a function so that it doesn't show in stack trace. However you can write your own function to sanitize the generic Exception::getTrace().

**Comment by ostrolucky** [comment]
Yep after this I hit https://github.com/merlinthemagic/MTS/issues/43 so it seems it progresses past the stage, also command seems ok. You should fix this though:

```
PHP Notice:  Undefined variable: returnPass in /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php on line 119
PHP Stack trace:
PHP   1. {main}() /home/g9735/IdeaProjects/MTS/index.php:0
PHP   2. MTS\Common\Devices\Types\Remotehost->getShell() /home/g9735/IdeaProjects/MTS/index.php:5
PHP   3. MTS\Common\Devices\Actions\Remote\Connections\Ssh->connectByUsername() /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Types/Remotehost.php:73
PHP   4. MTS\Common\Devices\Actions\Remote\Connections\Ssh->execute() /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php:18
PHP   5. MTS\Common\Devices\Actions\Remote\Connections\Ssh->connectByUsernameFromLinux() /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php:47
PHP Fatal error:  Uncaught Exception: MTS\Common\Devices\Actions\Remote\Connections\Ssh::connectByUsernameFromLinux>> Not Handled for Request Type: connectByUsername in /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php:130
```

**Comment by merlinthemagic** [comment]
once more. I keep screwing up

**Comment by ostrolucky** [comment]
```
PHP Fatal error:  Uncaught Exception: MTS\Common\Devices\Actions\Remote\Connections\Ssh::connectByUsernameFromLinux>> Not Handled for Request Type: connectByUsername in /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php:130
Stack trace:
#0 /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php(47): MTS\Common\Devices\Actions\Remote\Connections\Ssh->connectByUsernameFromLinux(Object(MTS\Common\Devices\Shells\Bash), 'potkany', NULL, 'sdaj.mtf.stuba....', 22, 30000)
#1 /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php(18): MTS\Common\Devices\Actions\Remote\Connections\Ssh->execute()
#2 /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Types/Remotehost.php(73): MTS\Common\Devices\Actions\Remote\Connections\Ssh->connectByUsername(Object(MTS\Common\Devices\Shells\Bash), 'anon', NULL, 'example.com....', 22)
#3 /home/g9735/IdeaProjects/MTS/index.php(5): MTS\Common\Devices\Types\Remotehost->getShell()
#4 {main}
  thrown in /home/g9735/IdeaProjects/MTS/MTS/Common/Devices/Actions/Remote/Connections/Ssh.php on line 130
```

Sorry I'm giving up on this project so won't provide more testing assistance.

**Comment by merlinthemagic** [comment]
Use: [MTM-SSH](https://github.com/merlinthemagic/MTM-SSH). MTS is not maintained.
